### ISSUE TITLE
Automation

### ISSUE THREAD

**Issue by clariion** [hckr/fb-post-screenshot#17]
Automation feature would be nice.

For example:
The tool is checking for new posts every 15  or 30 seconds and making a screenshot of it.

**Comment by hckr** [comment]
> The tool is checking for new posts every 15 or 30 seconds

New posts where? It'd be great if you could elaborate more on this idea

**Comment by clariion** [comment]
I am sorting most recent group posts with following link:
https://www.facebook.com/groups/xxxxxxxxxxxxxxxxxxxx/?sorting_setting=CHRONOLOGICAL

I would like to make a screenshot of the most recent post with your Addon automaticaly to my local folder on my PC.
(Addon could be able to refresh the page and to check for the most recent post and to save it automatically)

P.S. Could you also please implement an option in the "Options" to disable comments from post scrapping? (will donate you an amount)

cheers

**Comment by hckr** [comment]
>Could you also please implement an option in the "Options" to disable comments from post scrapping

So you'd like an option to capture only the post, without the comments below? It's not a problem, I'll implement it soon.

>Addon could be able to refresh the page and to check for the most recent post and to save it automatically

So what do you mean is you'd like to have an option in the add-on menu to enable "automation mode" for the current tab which would trigger a refresh (every n seconds configurable in options) and automatically start a screenshotting process if the newest post is different (by id) than the one previously saved? I'm open for suggestions on how would you like to use this feature, what interface would be useful etc.

**Comment by clariion** [comment]
> So you'd like an option to capture only the post, without the comments below? It's not a problem, I'll implement it soon.

Exactly :)

> So what do you mean is you'd like to have an option in the add-on menu to enable "automation mode" for the current tab which would trigger a refresh (every n seconds configurable in options) and automatically start a screenshotting process if the newest post is different (by id) than the one previously saved? I'm open for suggestions on how would you like to use this feature, what interface would be useful etc.

Correct! The addon should be able to refresh the facebook group-page every 15 or 30 seconds  and to make a screenshot only once of a post. (should be able to recognize by id - to avoid duplicates screenshots). 

My plan is to install firefox on a raspberry (raspbian linux) and to run this addon 24/7.
I have developed a python script, which will send the latest screenshot via telegram on my phone.

Why all this: I have a big facebook group, 800+ people and facebook notifications are coming late for two+ hours. (Group is about trading shares - very important too be fast)

**Comment by hckr** [comment]
I've published a new version with an experimental option – you need to enable this in add-ons options and then open a Facebook group and select an option from the add-ons menu.

**Comment by clariion** [comment]
Auto-refresh | done
Screenshot without comments | done
Automatic save of new posts | done

Well done! Thanks mate. Donation deserved.

Cheers

**Comment by hckr** [comment]
Thank you. :)

**Comment by hckr** [comment]
Just FYI: automatic save of new posts doesn't capture comments even if the other option is set to capture posts with comments, so you don't have to change it.

**Comment by clariion** [comment]
Aah okay. Thank you :-)
