### ISSUE TITLE
Option for font size

### ISSUE THREAD

**Issue by colorimeter** [hckr/fb-post-screenshot#19]
The rendering is currently independent of the zoom level of main window. It would be nice to have either a font size option or make the rendering zoom dependent in order to create better readable, high density screenshot images.

**Comment by hckr** [comment]
Hi, thank you for your input. I will investigate if the zoom level can be taken into account. From what I've quickly checked in [Firefox's screenshot utility](https://github.com/mozilla-services/screenshots/), it looks like it could be done quite easily. I wouldn't want to start with `font-size` hacking as it isn't that easy to change the font size in every post fragment, not mentioning the size of images, the width of the whole post, etc. To summarize: I'll try to respect the zoom level of the site (Facebook).

**Comment by colorimeter** [comment]
You are right, I've just checked changing the font size with FBPurity. It works, but ugly as hell. Respecting zoom level is the right way.

**Comment by hckr** [comment]
I've uploaded a new version to the Firefox Add-ons website. Please check if it works correctly. This functionality is disabled by default as I don't want to change the behavior for current users, you have to enable it in add-on options.

**Comment by colorimeter** [comment]
Perfect! Thank you for quick change!

I just add an idea silently that the most comfortable way of using this would be if I there was also an option to set zoom level for the rendering window instead of taking the it from the main window. I'd set it eg 200% and then I don't have to play with zoom in, screenshot, zoom out, but your plugin would do everything.

**Comment by hckr** [comment]
I also thought about it, I will implement it soon. I'm just not sure if it would be better as a selection list or just a text field. Firefox's zoom levels (> 100%) are: 110%, 120%, 133%, 150%, 170%, 200%, 240%, 300%. Do you think it'd be enough?

PS. The zoom level isn't really connected to the possibility of scaling the screenshot (AFAIK). I did it this way because I looked into the code of Firefox Screenshots tool and they dod it this way.

**Comment by colorimeter** [comment]
If I change it with mouse it steps 110,120,130... so every ten dividable percent seem to work.

About the option, I'd add a text field with just a comment something like: zoom value in percent (100 = default, 200 makes much better quality), and then anyone can play with if wants.

**Comment by hckr** [comment]
>If I change it with mouse it steps 110,120,130... so every ten dividable percent seem to work.

I always do it using keyboard (Ctrl and +) and then it increases differently O.o

**Comment by hckr** [comment]
I shipped a new version, please check.

**Comment by colorimeter** [comment]
Works flawlessly, thank you!
