### ISSUE TITLE
Reaction icon disappears for some comments.

### ISSUE THREAD

**Issue by martinramirezz** [hckr/fb-post-screenshot#20]
Hi again hckr, thanks a lot for the new bug fixes and improvements. The add-on is just looking better and better every day! I'm so happy and greateful for your great work.

I finally got some free time to write about a little aesthetic issue I found last month. It has probably been there already since March, but I just noticed it recently. The thing is that sometimes the add-on seems unable to capture the little reaction icon that should appear on the bottom-right corner of a comment when you react to it. It might show that you have reacted to the comment on the bottom-left corner, but without any icon on the bottom-right corner.

To reproduce it, you just have to go any post, either from within a group or a page, like or react to all or some of the comments, take a screenshot with the add-on and then look carefully at the generated screenshot and you will see that some comments will include the icon of your reaction on the bottom-right corner and others won't.

**Comment by hckr** [comment]
Hi, thanks for reporting this. I honestly haven't noticed it until now and it's very weird :open_mouth:. I'll try to fix this, but first I have to find the root cause.

**Comment by martinramirezz** [comment]
For a moment I thought that it's just a matter of speed. I might be entirely wrong here, but I got the impression that the icon takes some time to be generated, so it gets loaded after the screenshot is taken.

**Comment by hckr** [comment]
Yeah, but this doesn't fit to what happens behind the scenes in the popup window (behind the blue layer with status text):
1. Open post's permalink page.
2. Simulate clicks on all links to expand all content.
3. Save fragment of the page as images.

As you see, at least the reactions for comments in the first parts (of a longer post) should load – but they don't.
