### ISSUE TITLE
Screenshot wrongly saved without comments

### ISSUE THREAD

**Issue by gwendalyne** [hckr/fb-post-screenshot#29]
Hi,
I stayed at the classic Facebook interface also to be able to keep using your extension, which is very useful but unfortunately isn't supported by the new interface. I just noticed a problem that had never happened before: when I select "Save screenshot", it only saves the post without the comment section, even if among the options, under "Screenshot type", I have selected "post with all comments". Could you fix this issue, please?
Thanks for your attention!
Alessia

**Comment by Bisie** [comment]
Same here...
(also still stick to the 'old' interface)

So much love to save posts with all the comments... really miss it... :-(

Would be great to have this working again...

**Comment by Bisie** [comment]
Workaround:  reinstall older version (1.10.0 works fine for me in FF)
https://addons.mozilla.org/en-US/firefox/addon/facebook-post-screenshot/versions/

**Comment by hckr** [comment]
I've released a new version, it should be back to being somewhat usable. Please check and give feedback.

**Comment by gwendalyne** [comment]
Hi hckr,
now it's back to working properly, thanks a lot!
Regards,
Alessia

**Comment by Bisie** [comment]
Does it work with the new FB layout?

Op ma 6 jul. 2020 12:34 schreef gwendalyne <notifications@github.com>:

**Comment by hckr** [comment]
@Bisie No, I don't think so. Only the classic layout.
