### ISSUE TITLE
Does not expand replies and anonymous doesn't work

### ISSUE THREAD

**Issue by siffegh** [hckr/fb-post-screenshot#5]
Subject says it all. v1.6.3/FF 65.0.2/Win7 Pro SP1.

**Comment by hckr** [comment]
Yes, you're right – thanks for the info. However, it does work for some types of posts, e.g. in groups – that's the case I was testing. I didn't suspect it might work different on pages. I found an example to reproduce your issue (https://www.facebook.com/nytimes/posts/10151844131889999) and will now work on fixing it.

**Comment by siffegh** [comment]
It doesn't work for me in Groups, News feed, or Pages.  I am aware that FB is either testing or actually rolling out changes in the comment/reply system, so what might work for someone won't for another.  I wouldn't be at all surprised if that also affects anonymizing, but don't know for sure.

**Comment by hckr** [comment]
I've updated the extension on add-ons website. Please, check if it improved anything

**Comment by siffegh** [comment]
Yes, it works now everywhere I've tried. Can you make 'OP' stick through the shot instead of giving the OP a Profile #? Also, this happened a few times:

![image](https://user-images.githubusercontent.com/18728013/54097113-08459500-4385-11e9-8476-d29699ef6246.png)

**Comment by hckr** [comment]
>Can you make 'OP' stick through the shot

It worked that way, but not in all cases, as it seems.
Both should be ok now.

**Comment by siffegh** [comment]
Thanks - looking good! Any chance of outputting text instead of image?

**Comment by hckr** [comment]
What do you mean? Like an HTML page but only with one post cropped out?
I'd might consider it in the future, but I'm just not convinced yet – could you maybe file a separate issue with this concept?

BTW. There is a project allowing for reading text from images, but it is (probably) neither open-source, nor has support for Firefox (and probably is abandoned) – https://projectnaptha.com/
